sudo: required
services:
  - docker

before install:
  - docker build -t algorant/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true algorant/react-test npm test -- --coverage

after_success:
  - docker build -t algorant/multi-client ./client
  - docker build -t algorant/multi-nginx ./nginx
  - docker build -t algorant/multi-server ./server
  - docker build -t algorant/multi worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push skantastico/multi-client
  - docker push skantastico/multi-nginx
  - docker push skantastico/multi-server
  - docker push skantastico/multi-worker
